const ACTIONS_TYPES = {
  ADD_CHARACTER_TO_FAVORITES: 'ADD_CHARACTER_TO_FAVORITES',
  ADD_COMIC_TO_FAVORITES: 'ADD_COMIC_TO_FAVORITES',
  ADD_STORY_TO_FAVORITES: 'ADD_STORY_TO_FAVORITES',
  REMOVE_CHARACTER_OF_FAVORITES: 'REMOVE_CHARACTER_OF_FAVORITES',
  REMOVE_COMIC_OF_FAVORITES: 'REMOVE_COMIC_OF_FAVORITES',
  REMOVE_STORY_OF_FAVORITES: 'REMOVE_STORY_OF_FAVORITES',
  REMOVE_ALL_FAVORITES: 'REMOVE_ALL_FAVORITES',
};

export default ACTIONS_TYPES;
